name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    environment:
      name: 'github-pages'

    permissions:
      contents: write
  
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: make build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/final
