name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      pages: write      # to deploy to Pages
      id-token: write 
    
    steps:
      - name: Fetch files
        uses: actions/checkout@v3
          
      - name: Build
        run: make build
      
      - name: Upload
        uses: actions/upload-artifact@main
        with:
          name: 'github-pages'
          path: 'build/final'
      
      - name: Deploy
        uses: actions/deploy-pages@v1
