name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Fetch files
        uses: actions/checkout@v3
          
      - name: Build
        run: make build
      
      - name: Upload
        uses: actions/upload-artifact@main
      
      - name: Deploy
        uses: actions/deploy-pages@v1
